DB接続しないNablarchバッチに対応
nablarch/nablarch-fw-standalone pull request #17
Opened 2022-08-18 02:36 UTC by hiji

2022-08-18 07:49 UTC, kumagoro1202 requested changes

2022-08-18 07:49 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/handler/MultiThreadExecutionHandlerTest.java
> +            System.out.println("e => " + e);
消し忘れ？

2022-08-18 07:49 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/launcher/Main.java
> +        }
今までどこでも使われてなかったApplicationSettingLogUtil.getAppSettingsLogMsgが初めて日の目を見ましたねww

2022-08-18 23:43 UTC, hiji commented on src/test/java/nablarch/fw/handler/MultiThreadExecutionHandlerTest.java
> +            System.out.println("e => " + e);
すみません、削除漏れです。対応しました。

de9fccf0fe4d773ca20abf2cee65cb43704c0997

2022-08-19 01:22 UTC, kumagoro1202 approved these changes

2022-08-19 01:22 UTC, merged